/**
 * Cross-binding smoke: one prepared V2 plan, local and remote execution.
 *
 * The declared-schema bytes and plan bytes below are canonical fixtures
 * generated by the Rust contract crate; the Node side never builds or
 * mutates plans. Local execution runs through the native module against a
 * fresh isolated database; remote execution travels the versioned envelope
 * over HTTP to the `v2_smoke_server` example serving the same database,
 * and both paths must return byte-identical typed outcome JSON.
 */

import assert from "node:assert/strict";
import { spawn, type ChildProcess } from "node:child_process";
import { createRequire } from "node:module";
import net from "node:net";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import {
  TYPEDB_ADDRESS,
  TYPEDB_HTTP_PORT,
  TYPEDB_PASSWORD,
  TYPEDB_USERNAME,
} from "../common/index.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "../../..");
const _require = createRequire(import.meta.url);
const pkg = _require(packageRoot) as typeof import("../../../typescript/index.ts");
const native = pkg.loadNative() as never as Record<string, CallableFunction>;

const DECLARED_B64 =
  "eyJkZWNsYXJlZF9pZGVudGl0eSI6eyJhbGdvcml0aG0iOiJzaGEyNTYiLCJjYW5vbmljYWxpemF0aW9u" +
  "IjoidHlwZWJyaWRnZS5zY2hlbWEtY2Fub25pY2FsLWpzb24vdjEiLCJkaWdlc3QiOiJiZGFiNzEzOGE1" +
  "NzIzOGVlMjNkZmNlYjY5ZTdmMDk4OTNjZmE3YjUzNmQ5ZTcwMzU2ZDFhOTg2YTEzMjQ5OWZlIiwiZG9t" +
  "YWluIjoidHlwZWJyaWRnZS5zY2hlbWEuZGVjbGFyZWQtaWRlbnRpdHkifSwiZmFjdHMiOlt7ImtpbmQi" +
  "OiJ0eXBlIiwidmFsdWUiOnsiaWQiOnsia2luZCI6ImVudGl0eSIsImxhYmVsIjoic21va2UtcGVyc29u" +
  "In19fSx7ImtpbmQiOiJ0eXBlIiwidmFsdWUiOnsiaWQiOnsia2luZCI6ImF0dHJpYnV0ZSIsImxhYmVs" +
  "Ijoic21va2UtbmFtZSJ9fX0seyJraW5kIjoidmFsdWUiLCJ2YWx1ZSI6eyJpZCI6InNtb2tlLW5hbWUi" +
  "LCJ2YWx1ZV90eXBlIjoic3RyaW5nIn19LHsia2luZCI6Im93bnMiLCJ2YWx1ZSI6eyJpZCI6eyJhdHRy" +
  "aWJ1dGUiOiJzbW9rZS1uYW1lIiwib3duZXIiOnsia2luZCI6ImVudGl0eSIsImxhYmVsIjoic21va2Ut" +
  "cGVyc29uIn19fX1dLCJmb3JtYXRfdmVyc2lvbiI6MSwicmVxdWlyZWRfY2FwYWJpbGl0aWVzIjpbXX0=";
const PLAN_B64 =
  "eyJiaW5kaW5ncyI6W3siaWQiOjAsInZhcmlhYmxlIjoicGVyc29uIn0seyJpZCI6MSwidmFyaWFibGUi" +
  "OiJuYW1lIn1dLCJmb3JtYXQiOiJ0eXBlYnJpZGdlLnF1ZXJ5LXBsYW4vdjEiLCJmdW5jdGlvbnMiOltd" +
  "LCJpbnB1dHMiOltdLCJtYW5hZ2VkX3NlbWFudGljcyI6eyJhbGdvcml0aG0iOiJzaGEyNTYiLCJjYW5v" +
  "bmljYWxpemF0aW9uIjoidHlwZWJyaWRnZS5tYW5hZ2VkLXNlbWFudGljL3YxIiwiZGlnZXN0IjoiNTE2" +
  "MDViOWYyNWQ5MDFiNjlhOGVkMmIwNGQ2NGZkN2IwMWJkZTZjOTIwYzJiMzA3YzJiMDE2NDRhMDc2ODk0" +
  "YiIsImRvbWFpbiI6InR5cGVicmlkZ2Uuc2NoZW1hLm1hbmFnZWQtc2VtYW50aWMiLCJzZW1hbnRpY19w" +
  "cm9maWxlIjoidHlwZWRiLTMuMTIuMS92MSJ9LCJvdXRwdXQiOnsiY29sdW1ucyI6WzAsMV0sImtpbmQi" +
  "OiJyb3dzIn0sInBpcGVsaW5lIjpbeyJraW5kIjoibWF0Y2giLCJwYXR0ZXJucyI6W3siYmluZGluZyI6" +
  "MCwiaW5jbHVkZV9zdWJ0eXBlcyI6dHJ1ZSwia2luZCI6ImlzYSIsInR5cGVfaWQiOnsia2luZCI6ImVu" +
  "dGl0eSIsImxhYmVsIjoic21va2UtcGVyc29uIn19LHsiYXR0cmlidXRlIjoxLCJhdHRyaWJ1dGVfaWQi" +
  "OiJzbW9rZS1uYW1lIiwia2luZCI6ImhhcyIsIm93bmVyIjowfV19LHsia2luZCI6InNvcnQiLCJ0ZXJt" +
  "cyI6W3siYmluZGluZyI6MSwiZGlyZWN0aW9uIjoiYXNjZW5kaW5nIn1dfV0sInJlcXVpcmVkX2NhcGFi" +
  "aWxpdGllcyI6WyJxdWVyeS5vdXRwdXQucm93cyIsInF1ZXJ5LnBhdHRlcm4uaGFzIiwicXVlcnkucGF0" +
  "dGVybi5pc2EiLCJxdWVyeS5wYXR0ZXJuLmlzYS1zdWJ0eXBlcyIsInF1ZXJ5LnBsYW4iLCJxdWVyeS5z" +
  "dGFnZS5zb3J0Il19";
const SCOPE = "binding-smoke";
const PROFILE = "typedb-3.12.1/v1";

function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.listen(0, "127.0.0.1", () => {
      const address = probe.address();
      if (address === null || typeof address === "string") {
        reject(new Error("no probe address"));
        return;
      }
      probe.close(() => resolve(address.port));
    });
  });
}

async function waitForPort(
  port: number,
  server: ChildProcess,
  timeoutMs: number,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (server.exitCode !== null) {
      throw new Error(`smoke server exited early with code ${server.exitCode}`);
    }
    const reachable = await new Promise<boolean>((resolve) => {
      const socket = net.connect({ host: "127.0.0.1", port, timeout: 1000 });
      socket.once("connect", () => {
        socket.destroy();
        resolve(true);
      });
      socket.once("error", () => resolve(false));
      socket.once("timeout", () => {
        socket.destroy();
        resolve(false);
      });
    });
    if (reachable) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 200));
  }
  throw new Error("smoke server never became reachable");
}

test("prepared plan executes locally and remotely", async () => {
  const database = `tb_v2_node_smoke_${process.pid}_${Date.now()}`;
  native.ensureRustDatabase(
    TYPEDB_ADDRESS,
    database,
    TYPEDB_USERNAME,
    TYPEDB_PASSWORD,
    TYPEDB_HTTP_PORT,
    null,
  );
  const db = native.connectRustDatabase(
    TYPEDB_ADDRESS,
    database,
    TYPEDB_USERNAME,
    TYPEDB_PASSWORD,
    TYPEDB_HTTP_PORT,
    null,
  ) as never as Record<string, CallableFunction>;
  try {
    const schemaTx = db.transaction("schema") as never as Record<
      string,
      CallableFunction
    >;
    schemaTx.queryJson(
      "define attribute smoke-name, value string; " +
        "entity smoke-person, owns smoke-name;",
    );
    schemaTx.commit();
    const writeTx = db.transaction("write") as never as Record<
      string,
      CallableFunction
    >;
    writeTx.queryJson(
      'insert $a isa smoke-person, has smoke-name "ada"; ' +
        '$b isa smoke-person, has smoke-name "bob";',
    );
    writeTx.commit();

    const declared = Buffer.from(DECLARED_B64, "base64");
    const plan = Buffer.from(PLAN_B64, "base64");
    const invocation = JSON.stringify({ operation: "rows", rows: [] });
    const authority = native.queryV2Authority(declared, SCOPE, PROFILE);
    const local = native.queryV2ExecuteLocal(
      db,
      authority,
      plan,
      invocation,
    ) as string;
    assert.ok(local.includes('"ada"'), local);
    assert.ok(local.includes('"bob"'), local);

    const port = await freePort();
    const server = spawn(
      "cargo",
      [
        "run",
        "--quiet",
        "-p",
        "type-bridge-server",
        "--features",
        "v2-query",
        "--example",
        "v2_smoke_server",
      ],
      {
        cwd: path.resolve(packageRoot, "../.."),
        env: {
          ...process.env,
          SMOKE_TYPEDB_ADDRESS: TYPEDB_ADDRESS,
          SMOKE_TYPEDB_USERNAME: TYPEDB_USERNAME,
          SMOKE_TYPEDB_PASSWORD: TYPEDB_PASSWORD,
          SMOKE_DATABASE: database,
          SMOKE_DECLARED_B64: DECLARED_B64,
          SMOKE_SCOPE: SCOPE,
          SMOKE_PROFILE: PROFILE,
          SMOKE_PORT: String(port),
        },
        stdio: "ignore",
      },
    );
    try {
      await waitForPort(port, server, 300_000);
      const nonce = `binding-smoke-node-${process.pid}-${Date.now()}`;
      const request = native.queryV2EncodeRemoteRequest(
        authority,
        plan,
        invocation,
        nonce,
        100,
        1 << 20,
        30_000,
      ) as Buffer;
      const response = await fetch(`http://127.0.0.1:${port}/v2/query`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: new Uint8Array(request),
      });
      const body = Buffer.from(await response.arrayBuffer());
      const remote = native.queryV2DecodeRemoteOutcome(
        authority,
        plan,
        invocation,
        body,
        nonce,
        100,
        1 << 20,
      ) as string;
      assert.equal(remote, local);
    } finally {
      server.kill("SIGKILL");
    }
  } finally {
    db.deleteDatabase();
  }
});
