//! V1 compatibility re-exports for shared typed-plan structural limits.

pub use type_bridge_contract::limits::{
    CANONICAL_STRUCTURAL_LIMITS, MAX_ALLOWED_CROSS_JOINS, MAX_BINDINGS,
    MAX_BOOLEAN_TERMS, MAX_COLLECTION_ORDER_TERMS, MAX_DIAGNOSTIC_BYTES,
    MAX_ORDER_TERMS, MAX_OUTPUT_NAME_BYTES, MAX_PREDICATE_DEPTH,
    MAX_PREDICATE_NODES, MAX_SELECTED_SLOTS, MAX_SEMANTIC_ID_BYTES,
    StructuralLimits,
};
