//! Render the reviewable migration `.py` from authoring operations.
//!
//! Ports the historical Python renderer byte-for-byte: module docstring with
//! an explicit `generated_at` timestamp, import block, snapshot symbol
//! resolution with cross-version aliasing, and per-operation source. `Add*`
//! operations reference the post-version snapshot bindings, removals the
//! pre-version bindings, with `ref.*` fallbacks when a label is not present
//! in the corresponding snapshot schema.

use std::collections::{BTreeMap, BTreeSet};

use type_bridge_core_lib::bindgen::python_class_name;
use type_bridge_orm::Annotation;
use type_bridge_orm::schema::info::SchemaInfo;

use crate::spec::{DeclaredMigrationIntent, OperationSpec};

/// Everything needed to render one migration `.py`.
pub struct PythonRenderRequest<'a> {
    /// Ordered authoring operations.
    pub operations: &'a [OperationSpec],
    /// Migrations package name (the migrations directory name).
    pub app_label: &'a str,
    /// Migration name suffix (e.g. `add_assignment`).
    pub name: &'a str,
    /// `(app_label, migration_name)` dependencies.
    pub dependencies: &'a [(String, String)],
    /// Timestamp text embedded verbatim in the module docstring.
    ///
    /// Passed explicitly so identical inputs produce byte-identical output.
    pub generated_at: &'a str,
    /// Previous snapshot version (`v000{N-1}`), if any.
    pub pre_version: Option<&'a str>,
    /// Snapshot version generated together with this migration (`v000N`).
    pub post_version: &'a str,
    /// Schema the pre-version snapshot was generated from.
    pub base: &'a SchemaInfo,
    /// Schema the post-version snapshot is generated from.
    pub target: &'a SchemaInfo,
    /// Explicit semantic-transition identity, when this version was declared
    /// despite having no physical or data operations.
    pub declared_intent: Option<&'a DeclaredMigrationIntent>,
}

/// Render the complete migration `.py` source.
///
/// # Errors
///
/// [`MigrationError::UnsupportedChange`] when the operation list contains a
/// variant that has no faithful `.py` authoring form (`DefineSchema`,
/// TypeQL-only `CopyAttribute`, `RenameAttribute`).
pub fn render_migration_python(request: &PythonRenderRequest<'_>) -> crate::Result<String> {
    let resolver = SymbolResolver::new(request);
    let description = if request.operations.is_empty() && request.declared_intent.is_some() {
        "declared semantic transition".to_string()
    } else {
        describe_operations(request.operations)
    };
    let class_name = migration_class_name(request.name);
    let dependencies = render_dependencies(request.dependencies);
    let imports = resolver.render_imports(request.app_label);
    let operations = render_operations(request.operations, &resolver)?;
    let intent_section = request.declared_intent.map_or_else(String::new, |intent| {
        format!(
            "Declared semantic transition: {} {}\n\n",
            intent.scheme(),
            intent.identity()
        )
    });

    Ok(format!(
        "\"\"\"Migration: {description}\n\n{intent_section}Auto-generated by type_bridge on {generated_at}\n\"\"\"\n\n{imports}\n\n\nclass {class_name}(Migration):\n    \"\"\"Migration: {description}\"\"\"\n\n    dependencies: ClassVar[list[tuple[str, str]]] = {dependencies}\n\n{operations}\n",
        generated_at = request.generated_at,
    ))
}

/// Convert a migration name suffix into its class name
/// (`add_company` -> `AddCompanyMigration`).
pub fn migration_class_name(name: &str) -> String {
    let camel: String = name
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => {
                    first.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase()
                }
                None => String::new(),
            }
        })
        .collect();
    format!("{camel}Migration")
}

/// Which side of the schema change an operation's symbols resolve against.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Side {
    Pre,
    Post,
}

/// The label kinds a snapshot symbol can have.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Kind {
    Entity,
    Relation,
    Attribute,
}

impl Kind {
    fn submodule(self) -> &'static str {
        match self {
            Kind::Entity => "entities",
            Kind::Relation => "relations",
            Kind::Attribute => "attributes",
        }
    }
}

struct SymbolResolver<'a> {
    pre_version: Option<&'a str>,
    post_version: &'a str,
    base: &'a SchemaInfo,
    target: &'a SchemaInfo,
    /// version -> submodule -> class names.
    imports: BTreeMap<String, BTreeMap<&'static str, BTreeSet<String>>>,
    /// (version, symbol) -> alias.
    aliases: BTreeMap<(String, String), String>,
}

impl<'a> SymbolResolver<'a> {
    fn new(request: &PythonRenderRequest<'a>) -> Self {
        let mut resolver = SymbolResolver {
            pre_version: request.pre_version,
            post_version: request.post_version,
            base: request.base,
            target: request.target,
            imports: BTreeMap::new(),
            aliases: BTreeMap::new(),
        };
        for op in request.operations {
            resolver.collect(op);
        }
        resolver.compute_aliases();
        resolver
    }

    fn side_of(op: &OperationSpec) -> Side {
        match op {
            // Backfills run against the post-change schema (the destination
            // ownership exists only there), so the owner resolves post-side.
            OperationSpec::AddAttribute { .. }
            | OperationSpec::AddEntity { .. }
            | OperationSpec::AddRelation { .. }
            | OperationSpec::AddOwnership { .. }
            | OperationSpec::AddRole { .. }
            | OperationSpec::AddRolePlayer { .. }
            | OperationSpec::CopyAttribute { .. } => Side::Post,
            _ => Side::Pre,
        }
    }

    fn schema_of(&self, side: Side) -> &SchemaInfo {
        match side {
            Side::Pre => self.base,
            Side::Post => self.target,
        }
    }

    fn version_of(&self, side: Side) -> Option<&str> {
        match side {
            Side::Pre => self.pre_version,
            Side::Post => Some(self.post_version),
        }
    }

    /// The kind of `label` in the given side's schema, if it exists there.
    fn kind_in(&self, side: Side, label: &str) -> Option<Kind> {
        let schema = self.schema_of(side);
        if schema.relations.contains_key(label) {
            Some(Kind::Relation)
        } else if schema.entities.contains_key(label) {
            Some(Kind::Entity)
        } else if schema.attributes.contains_key(label) {
            Some(Kind::Attribute)
        } else {
            None
        }
    }

    fn record(&mut self, side: Side, label: &str) {
        let Some(kind) = self.kind_in(side, label) else {
            return;
        };
        let Some(version) = self.version_of(side) else {
            return;
        };
        self.imports
            .entry(version.to_string())
            .or_default()
            .entry(kind.submodule())
            .or_default()
            .insert(python_class_name(label));
    }

    fn collect(&mut self, op: &OperationSpec) {
        let side = Self::side_of(op);
        match op {
            OperationSpec::AddEntity { entity } => self.record(side, &entity.type_name),
            OperationSpec::RemoveEntity { type_name } => self.record(side, type_name),
            OperationSpec::AddRelation { relation } => self.record(side, &relation.type_name),
            OperationSpec::RemoveRelation { type_name } => self.record(side, type_name),
            OperationSpec::AddAttribute { attribute } => self.record(side, &attribute.attr_name),
            OperationSpec::RemoveAttribute { attr_name } => self.record(side, attr_name),
            OperationSpec::AddOwnership {
                owner_type,
                attribute,
            } => {
                self.record(side, owner_type);
                self.record(side, &attribute.attr_name);
            }
            OperationSpec::RemoveOwnership {
                owner_type,
                attr_name,
            }
            | OperationSpec::ModifyOwnership {
                owner_type,
                attr_name,
                ..
            } => {
                self.record(side, owner_type);
                self.record(side, attr_name);
            }
            OperationSpec::AddRole { relation_type, .. }
            | OperationSpec::RemoveRole { relation_type, .. }
            | OperationSpec::AddRolePlayer { relation_type, .. }
            | OperationSpec::RemoveRolePlayer { relation_type, .. } => {
                self.record(side, relation_type);
            }
            OperationSpec::CopyAttribute { owner, .. } => {
                if let Some(owner) = owner {
                    self.record(side, owner);
                }
            }
            OperationSpec::ModifyTypeAnnotations { type_name, .. } => {
                self.record(side, type_name);
            }
            OperationSpec::ModifyRoleAnnotations { relation_type, .. } => {
                self.record(side, relation_type);
            }
            OperationSpec::DefineSchema { .. }
            | OperationSpec::RunTypeql { .. }
            | OperationSpec::RenameAttribute { .. } => {}
        }
    }

    /// Colliding class names across versions: the latest version keeps the
    /// bare symbol, earlier versions import it as `{Symbol}{VERSION}`.
    fn compute_aliases(&mut self) {
        let mut symbol_versions: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        for (version, submodules) in &self.imports {
            for symbols in submodules.values() {
                for symbol in symbols {
                    symbol_versions
                        .entry(symbol.clone())
                        .or_default()
                        .insert(version.clone());
                }
            }
        }
        for (symbol, versions) in symbol_versions {
            if versions.len() > 1 {
                let latest = versions.iter().next_back().cloned().unwrap_or_default();
                for version in versions {
                    if version != latest {
                        let alias = format!("{symbol}{}", version.to_uppercase());
                        self.aliases.insert((version, symbol.clone()), alias);
                    }
                }
            }
        }
    }

    /// Resolve a type/attribute reference into rendered source: the snapshot
    /// symbol when the label exists in the side's snapshot, otherwise a
    /// `ref.*` literal.
    fn reference(&self, side: Side, label: &str, fallback: Kind) -> String {
        if let (Some(_), Some(version)) = (self.kind_in(side, label), self.version_of(side)) {
            let symbol = python_class_name(label);
            let aliased = self
                .aliases
                .get(&(version.to_string(), symbol.clone()))
                .cloned()
                .unwrap_or(symbol);
            return aliased;
        }
        let constructor = match fallback {
            Kind::Entity => "ref.entity",
            Kind::Relation => "ref.relation",
            Kind::Attribute => "ref.attribute",
        };
        format!("{constructor}({})", py_repr(label))
    }

    /// Kind of an annotation-subject label (entity, relation, or attribute):
    /// what the side's schema says, falling back to the other side.
    fn subject_kind(&self, side: Side, label: &str) -> Option<Kind> {
        let other = match side {
            Side::Pre => Side::Post,
            Side::Post => Side::Pre,
        };
        self.kind_in(side, label)
            .or_else(|| self.kind_in(other, label))
    }

    /// Fallback kind for an owner label: prefer what the side's schema says,
    /// then what the other side's schema says, defaulting to entity.
    fn owner_kind(&self, side: Side, label: &str) -> Kind {
        let other = match side {
            Side::Pre => Side::Post,
            Side::Post => Side::Pre,
        };
        match self
            .kind_in(side, label)
            .or_else(|| self.kind_in(other, label))
        {
            Some(Kind::Relation) => Kind::Relation,
            _ => Kind::Entity,
        }
    }

    fn render_imports(&self, app_label: &str) -> String {
        let mut lines = vec![
            "from typing import ClassVar".to_string(),
            String::new(),
            "from type_bridge.migration import Migration".to_string(),
            "from type_bridge.migration.operations import Operation".to_string(),
            "from type_bridge.migration import operations as ops, ref".to_string(),
        ];
        if !self.imports.is_empty() {
            lines.push(String::new());
            for (version, submodules) in &self.imports {
                let symbols: BTreeSet<&String> = submodules.values().flatten().collect();
                let parts: Vec<String> = symbols
                    .into_iter()
                    .map(
                        |symbol| match self.aliases.get(&(version.clone(), symbol.clone())) {
                            Some(alias) => format!("{symbol} as {alias}"),
                            None => symbol.clone(),
                        },
                    )
                    .collect();
                lines.push(format!(
                    "from {app_label}.snapshots.{version} import {}",
                    parts.join(", ")
                ));
            }
        }
        lines.join("\n")
    }
}

fn render_operations(
    operations: &[OperationSpec],
    resolver: &SymbolResolver<'_>,
) -> crate::Result<String> {
    if operations.is_empty() {
        return Ok("    operations: ClassVar[list[Operation]] = []".to_string());
    }
    let mut lines = vec!["    operations: ClassVar[list[Operation]] = [".to_string()];
    for op in operations {
        lines.push(format!("        {},", render_operation(op, resolver)?));
    }
    lines.push("    ]".to_string());
    Ok(lines.join("\n"))
}

fn render_operation(op: &OperationSpec, resolver: &SymbolResolver<'_>) -> crate::Result<String> {
    let side = SymbolResolver::side_of(op);
    Ok(match op {
        OperationSpec::AddAttribute { attribute } => format!(
            "ops.AddAttribute({})",
            resolver.reference(side, &attribute.attr_name, Kind::Attribute)
        ),
        OperationSpec::RemoveAttribute { attr_name } => format!(
            "ops.RemoveAttribute({})",
            resolver.reference(side, attr_name, Kind::Attribute)
        ),
        OperationSpec::AddEntity { entity } => format!(
            "ops.AddEntity({})",
            resolver.reference(side, &entity.type_name, Kind::Entity)
        ),
        OperationSpec::RemoveEntity { type_name } => format!(
            "ops.RemoveEntity({})",
            resolver.reference(side, type_name, Kind::Entity)
        ),
        OperationSpec::AddRelation { relation } => format!(
            "ops.AddRelation({})",
            resolver.reference(side, &relation.type_name, Kind::Relation)
        ),
        OperationSpec::RemoveRelation { type_name } => format!(
            "ops.RemoveRelation({})",
            resolver.reference(side, type_name, Kind::Relation)
        ),
        OperationSpec::AddOwnership {
            owner_type,
            attribute,
        } => {
            let owner = resolver.reference(side, owner_type, resolver.owner_kind(side, owner_type));
            let attr = resolver.reference(side, &attribute.attr_name, Kind::Attribute);
            let mut parts = vec![owner, attr];
            parts.extend(add_ownership_kwargs(&attribute.annotations));
            format!("ops.AddOwnership({})", parts.join(", "))
        }
        OperationSpec::RemoveOwnership {
            owner_type,
            attr_name,
        } => format!(
            "ops.RemoveOwnership({}, {})",
            resolver.reference(side, owner_type, resolver.owner_kind(side, owner_type)),
            resolver.reference(side, attr_name, Kind::Attribute)
        ),
        OperationSpec::ModifyOwnership {
            owner_type,
            attr_name,
            old_annotations,
            new_annotations,
        } => format!(
            "ops.ModifyOwnership({}, {}, old_annotations={}, new_annotations={})",
            resolver.reference(side, owner_type, resolver.owner_kind(side, owner_type)),
            resolver.reference(side, attr_name, Kind::Attribute),
            py_repr(old_annotations),
            py_repr(new_annotations)
        ),
        OperationSpec::AddRole {
            relation_type,
            role,
        } => format!(
            "ops.AddRole({}, {}, {})",
            resolver.reference(side, relation_type, Kind::Relation),
            py_repr(&role.role_name),
            py_repr_list(&role.player_type_names)
        ),
        OperationSpec::RemoveRole {
            relation_type,
            role_name,
        } => format!(
            "ops.RemoveRole({}, {})",
            resolver.reference(side, relation_type, Kind::Relation),
            py_repr(role_name)
        ),
        OperationSpec::AddRolePlayer {
            relation_type,
            role_name,
            player_type_name,
        } => format!(
            "ops.AddRolePlayer({}, {}, {})",
            resolver.reference(side, relation_type, Kind::Relation),
            py_repr(role_name),
            py_repr(player_type_name)
        ),
        OperationSpec::RemoveRolePlayer {
            relation_type,
            role_name,
            player_type_name,
        } => format!(
            "ops.RemoveRolePlayer({}, {}, {})",
            resolver.reference(side, relation_type, Kind::Relation),
            py_repr(role_name),
            py_repr(player_type_name)
        ),
        OperationSpec::ModifyTypeAnnotations {
            type_name,
            old_doc,
            new_doc,
            old_meta,
            new_meta,
        } => {
            let fallback = resolver
                .subject_kind(side, type_name)
                .unwrap_or(Kind::Entity);
            format!(
                "ops.ModifyTypeAnnotations({}, old_doc={}, new_doc={}, old_meta={}, new_meta={})",
                resolver.reference(side, type_name, fallback),
                py_repr_opt(old_doc.as_deref()),
                py_repr_opt(new_doc.as_deref()),
                py_repr_dict(old_meta),
                py_repr_dict(new_meta)
            )
        }
        OperationSpec::ModifyRoleAnnotations {
            relation_type,
            role_name,
            old_doc,
            new_doc,
            old_meta,
            new_meta,
        } => format!(
            "ops.ModifyRoleAnnotations({}, {}, old_doc={}, new_doc={}, old_meta={}, new_meta={})",
            resolver.reference(side, relation_type, Kind::Relation),
            py_repr(role_name),
            py_repr_opt(old_doc.as_deref()),
            py_repr_opt(new_doc.as_deref()),
            py_repr_dict(old_meta),
            py_repr_dict(new_meta)
        ),
        OperationSpec::RunTypeql { forward, reverse } => match reverse {
            Some(reverse) => format!(
                "ops.RunTypeQL(forward={}, reverse={})",
                py_repr(forward),
                py_repr(reverse)
            ),
            None => format!("ops.RunTypeQL(forward={})", py_repr(forward)),
        },
        // `ops.RenameAttribute` is a non-executable placeholder (the planner
        // refuses to lower it), so rendering it would author an artifact that
        // can never run. Renames are authored as `attribute_renames`
        // directives, which expand into executable primitives.
        OperationSpec::RenameAttribute { .. } => {
            return Err(crate::error::MigrationError::UnsupportedChange {
                type_name: "<operations>".to_string(),
                change: "rename_attribute has no executable lowering; pass the rename as an \
                         attribute_renames directive instead"
                    .to_string(),
            });
        }
        OperationSpec::CopyAttribute {
            owner: Some(owner),
            source: Some(source),
            dest: Some(dest),
            filter,
            ..
        } => {
            let mut parts = vec![
                resolver.reference(side, owner, resolver.owner_kind(side, owner)),
                format!("source={}", py_repr(source)),
                format!("dest={}", py_repr(dest)),
            ];
            if let Some(filter) = filter {
                parts.push(format!("filter={}", py_repr(filter)));
            }
            format!("ops.CopyAttribute({})", parts.join(", "))
        }
        // A TypeQL-only CopyAttribute cannot round-trip to a faithful
        // `ops.CopyAttribute(...)` source form, and rendering it as RunTypeQL
        // would change its execution step kind (backfill vs plain write).
        // DefineSchema is a model-initial construct that never flows through
        // authoring.
        OperationSpec::CopyAttribute { .. } => {
            return Err(crate::error::MigrationError::UnsupportedChange {
                type_name: "<operations>".to_string(),
                change: "lowered copy_attribute has no .py authoring form; \
                         provide the structured owner/source/dest fields"
                    .to_string(),
            });
        }
        OperationSpec::DefineSchema { .. } => {
            return Err(crate::error::MigrationError::UnsupportedChange {
                type_name: "<operations>".to_string(),
                change: "define_schema has no .py authoring form".to_string(),
            });
        }
    })
}

/// Render `AddOwnership` keyword arguments from ownership annotations,
/// mirroring the historical precedence: `key` and `unique` are exclusive
/// shorthands, `@card(0..1)` renders as `optional=True`, and any other
/// cardinality spells out `card_min`/`card_max`.
fn add_ownership_kwargs(annotations: &[Annotation]) -> Vec<String> {
    let has_key = annotations.iter().any(|a| matches!(a, Annotation::Key));
    if has_key {
        return vec!["key=True".to_string()];
    }
    let has_unique = annotations.iter().any(|a| matches!(a, Annotation::Unique));
    if has_unique {
        return vec!["unique=True".to_string()];
    }
    let card = annotations.iter().find_map(|a| match a {
        Annotation::Card(min, max) => Some((*min, *max)),
        _ => None,
    });
    match card {
        Some((0, Some(1))) => vec!["optional=True".to_string()],
        Some((min, max)) => {
            let mut kwargs = Vec::new();
            if min == 0 {
                kwargs.push("optional=True".to_string());
            }
            kwargs.push(format!("card_min={min}"));
            if let Some(max) = max {
                kwargs.push(format!("card_max={max}"));
            }
            kwargs
        }
        None => Vec::new(),
    }
}

fn describe_operations(operations: &[OperationSpec]) -> String {
    let mut parts: Vec<String> = Vec::new();
    for op in operations.iter().take(3) {
        match op {
            OperationSpec::AddEntity { entity } => {
                parts.push(format!("add {}", entity.type_name));
            }
            OperationSpec::AddAttribute { attribute } => {
                parts.push(format!("add {}", attribute.attr_name));
            }
            OperationSpec::AddRelation { relation } => {
                parts.push(format!("add {}", relation.type_name));
            }
            OperationSpec::AddOwnership {
                owner_type,
                attribute,
            } => {
                parts.push(format!("add {} to {}", attribute.attr_name, owner_type));
            }
            _ => {}
        }
    }
    if operations.len() > 3 {
        parts.push(format!("and {} more", operations.len() - 3));
    }
    if parts.is_empty() {
        "schema changes".to_string()
    } else {
        parts.join(", ")
    }
}

fn render_dependencies(dependencies: &[(String, String)]) -> String {
    if dependencies.is_empty() {
        return "[]".to_string();
    }
    let parts: Vec<String> = dependencies
        .iter()
        .map(|(app, name)| format!("({}, {})", py_repr(app), py_repr(name)))
        .collect();
    format!("[{}]", parts.join(", "))
}

/// Render a Python string literal exactly like CPython's `repr()`.
///
/// Single quotes by default; double quotes when the text contains a single
/// quote but no double quote. Backslashes, quotes, and the common control
/// characters are escaped the way `repr()` escapes them.
pub fn py_repr(text: &str) -> String {
    let use_double = text.contains('\'') && !text.contains('"');
    let quote = if use_double { '"' } else { '\'' };
    let mut out = String::with_capacity(text.len() + 2);
    out.push(quote);
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c == quote => {
                out.push('\\');
                out.push(c);
            }
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\x{:02x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push(quote);
    out
}

fn py_repr_list(items: &[String]) -> String {
    let parts: Vec<String> = items.iter().map(|item| py_repr(item)).collect();
    format!("[{}]", parts.join(", "))
}

fn py_repr_opt(text: Option<&str>) -> String {
    match text {
        Some(text) => py_repr(text),
        None => "None".to_string(),
    }
}

fn py_repr_dict(map: &BTreeMap<String, String>) -> String {
    let parts: Vec<String> = map
        .iter()
        .map(|(key, value)| format!("{}: {}", py_repr(key), py_repr(value)))
        .collect();
    format!("{{{}}}", parts.join(", "))
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use type_bridge_orm::ValueType;
    use type_bridge_orm::schema::info::{
        AttributeSchemaEntry, EntitySchemaEntry, OwnedAttributeEntry,
    };

    use super::*;

    fn entity(name: &str, owned_attributes: Vec<OwnedAttributeEntry>) -> EntitySchemaEntry {
        EntitySchemaEntry {
            type_name: name.to_string(),
            is_abstract: false,
            parent_type: None,
            owned_attributes,
            plays_cardinalities: BTreeMap::new(),
            doc: None,
            meta: BTreeMap::new(),
        }
    }

    fn owned_optional(name: &str) -> OwnedAttributeEntry {
        OwnedAttributeEntry {
            attr_name: name.to_string(),
            value_type: ValueType::String,
            annotations: vec![Annotation::Card(0, Some(1))],
            is_ordered: false,
            doc: None,
            meta: BTreeMap::new(),
        }
    }

    fn schema_with(entities: Vec<EntitySchemaEntry>, attributes: Vec<&str>) -> SchemaInfo {
        let mut info = SchemaInfo::default();
        for entry in entities {
            info.entities.insert(entry.type_name.clone(), entry);
        }
        for name in attributes {
            info.attributes.insert(
                name.to_string(),
                AttributeSchemaEntry::new(name, ValueType::String),
            );
        }
        info
    }

    #[test]
    fn renders_add_age_migration_in_historical_format() {
        let base = schema_with(vec![entity("person", vec![])], vec!["name"]);
        let target = schema_with(
            vec![entity("person", vec![owned_optional("age")])],
            vec!["name", "age"],
        );
        let operations = vec![
            OperationSpec::AddAttribute {
                attribute: AttributeSchemaEntry::new("age", ValueType::Long),
            },
            OperationSpec::AddOwnership {
                owner_type: "person".to_string(),
                attribute: owned_optional("age"),
            },
        ];
        let dependencies = vec![("migrations".to_string(), "0001_initial".to_string())];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "add_age",
            dependencies: &dependencies,
            generated_at: "2026-07-13T00:00:00+00:00",
            pre_version: Some("v0001"),
            post_version: "v0002",
            base: &base,
            target: &target,
            declared_intent: None,
        })
        .expect("render should succeed");

        let expected = concat!(
            "\"\"\"Migration: add age, add age to person\n",
            "\n",
            "Auto-generated by type_bridge on 2026-07-13T00:00:00+00:00\n",
            "\"\"\"\n",
            "\n",
            "from typing import ClassVar\n",
            "\n",
            "from type_bridge.migration import Migration\n",
            "from type_bridge.migration.operations import Operation\n",
            "from type_bridge.migration import operations as ops, ref\n",
            "\n",
            "from migrations.snapshots.v0002 import Age, Person\n",
            "\n",
            "\n",
            "class AddAgeMigration(Migration):\n",
            "    \"\"\"Migration: add age, add age to person\"\"\"\n",
            "\n",
            "    dependencies: ClassVar[list[tuple[str, str]]] = [('migrations', '0001_initial')]\n",
            "\n",
            "    operations: ClassVar[list[Operation]] = [\n",
            "        ops.AddAttribute(Age),\n",
            "        ops.AddOwnership(Person, Age, optional=True),\n",
            "    ]\n",
        );
        assert_eq!(rendered, expected);
    }

    #[test]
    fn removals_resolve_pre_version_symbols_and_fall_back_to_refs() {
        let base = schema_with(vec![entity("customer", vec![])], vec!["email"]);
        let target = SchemaInfo::default();
        let operations = vec![
            OperationSpec::RemoveOwnership {
                owner_type: "customer".to_string(),
                attr_name: "email".to_string(),
            },
            OperationSpec::RemoveEntity {
                type_name: "customer".to_string(),
            },
            // Not present in the base schema: must fall back to ref.*.
            OperationSpec::RemoveAttribute {
                attr_name: "ghost-code".to_string(),
            },
        ];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "drop_customer",
            dependencies: &[],
            generated_at: "t",
            pre_version: Some("v0003"),
            post_version: "v0004",
            base: &base,
            target: &target,
            declared_intent: None,
        })
        .expect("render should succeed");

        assert!(rendered.contains("from migrations.snapshots.v0003 import Customer, Email"));
        assert!(rendered.contains("ops.RemoveOwnership(Customer, Email),"));
        assert!(rendered.contains("ops.RemoveEntity(Customer),"));
        assert!(rendered.contains("ops.RemoveAttribute(ref.attribute('ghost-code')),"));
    }

    #[test]
    fn colliding_symbols_alias_the_older_version() {
        // `person` exists in both snapshots and is referenced on both sides:
        // the newer version keeps the bare name, the older one is aliased.
        let base = schema_with(
            vec![entity("person", vec![owned_optional("age")])],
            vec!["age"],
        );
        let target = schema_with(vec![entity("person", vec![])], vec!["age", "nickname"]);
        let operations = vec![
            OperationSpec::AddOwnership {
                owner_type: "person".to_string(),
                attribute: owned_optional("nickname"),
            },
            OperationSpec::RemoveOwnership {
                owner_type: "person".to_string(),
                attr_name: "age".to_string(),
            },
        ];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "swap_ownership",
            dependencies: &[],
            generated_at: "t",
            pre_version: Some("v0001"),
            post_version: "v0002",
            base: &base,
            target: &target,
            declared_intent: None,
        })
        .expect("render should succeed");

        assert!(
            rendered.contains("from migrations.snapshots.v0001 import Age, Person as PersonV0001"),
            "older version must alias the colliding symbol: {rendered}"
        );
        assert!(rendered.contains("ops.RemoveOwnership(PersonV0001, Age),"));
        assert!(!rendered.contains("ops.AddOwnership(person"));
    }

    #[test]
    fn initial_migration_has_no_pre_version_imports() {
        let target = schema_with(vec![entity("person", vec![])], vec!["name"]);
        let operations = vec![
            OperationSpec::AddAttribute {
                attribute: AttributeSchemaEntry::new("name", ValueType::String),
            },
            OperationSpec::AddEntity {
                entity: entity("person", vec![]),
            },
        ];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "initial",
            dependencies: &[],
            generated_at: "t",
            pre_version: None,
            post_version: "v0001",
            base: &SchemaInfo::default(),
            target: &target,
            declared_intent: None,
        })
        .expect("render should succeed");

        assert!(rendered.contains("from migrations.snapshots.v0001 import Name, Person"));
        assert!(!rendered.contains("v0000"));
        assert!(rendered.contains("class InitialMigration(Migration):"));
    }

    #[test]
    fn run_typeql_renders_python_repr_strings() {
        let operations = vec![OperationSpec::RunTypeql {
            forward: "define\nattribute code, value string;".to_string(),
            reverse: None,
        }];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "custom",
            dependencies: &[],
            generated_at: "t",
            pre_version: None,
            post_version: "v0001",
            base: &SchemaInfo::default(),
            target: &SchemaInfo::default(),
            declared_intent: None,
        })
        .expect("render should succeed");

        assert!(
            rendered.contains("ops.RunTypeQL(forward='define\\nattribute code, value string;'),")
        );
    }

    #[test]
    fn py_repr_matches_cpython_quoting_rules() {
        assert_eq!(py_repr("plain"), "'plain'");
        assert_eq!(py_repr("with'single"), "\"with'single\"");
        assert_eq!(py_repr("both'\"quotes"), "'both\\'\"quotes'");
        assert_eq!(
            py_repr("line\nbreak\ttab\\slash"),
            "'line\\nbreak\\ttab\\\\slash'"
        );
    }

    #[test]
    fn structured_copy_attribute_renders_faithful_source() {
        let mut target = SchemaInfo::default();
        target.entities.insert(
            "person".to_string(),
            type_bridge_orm::schema::info::EntitySchemaEntry {
                type_name: "person".to_string(),
                is_abstract: false,
                parent_type: None,
                owned_attributes: vec![],
                plays_cardinalities: std::collections::BTreeMap::new(),
                doc: None,
                meta: std::collections::BTreeMap::new(),
            },
        );
        let operations = vec![OperationSpec::CopyAttribute {
            owner: Some("person".to_string()),
            source: Some("legacy-name".to_string()),
            dest: Some("display-name".to_string()),
            filter: Some("$x has age $a;".to_string()),
            forward: None,
            reverse: None,
        }];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "backfill",
            dependencies: &[],
            generated_at: "t",
            pre_version: None,
            post_version: "v0002",
            base: &SchemaInfo::default(),
            target: &target,
            declared_intent: None,
        })
        .expect("render should succeed");

        // The owner resolves to the post-side snapshot symbol; source/dest
        // stay plain labels because the Python op takes them as strings.
        assert!(rendered.contains(
            "ops.CopyAttribute(Person, source='legacy-name', dest='display-name', filter='$x has age $a;'),"
        ));
        assert!(rendered.contains("from migrations.snapshots.v0002 import Person"));
    }

    #[test]
    fn structured_copy_attribute_falls_back_to_ref_for_unknown_owner() {
        let operations = vec![OperationSpec::CopyAttribute {
            owner: Some("person".to_string()),
            source: Some("legacy-name".to_string()),
            dest: Some("display-name".to_string()),
            filter: None,
            forward: None,
            reverse: None,
        }];

        let rendered = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "backfill",
            dependencies: &[],
            generated_at: "t",
            pre_version: None,
            post_version: "v0002",
            base: &SchemaInfo::default(),
            target: &SchemaInfo::default(),
            declared_intent: None,
        })
        .expect("render should succeed");

        assert!(rendered.contains(
            "ops.CopyAttribute(ref.entity('person'), source='legacy-name', dest='display-name'),"
        ));
    }

    #[test]
    fn lowered_copy_attribute_is_rejected() {
        let operations = vec![OperationSpec::CopyAttribute {
            owner: None,
            source: None,
            dest: None,
            filter: None,
            forward: Some("match ...".to_string()),
            reverse: None,
        }];

        let error = render_migration_python(&PythonRenderRequest {
            operations: &operations,
            app_label: "migrations",
            name: "copy",
            dependencies: &[],
            generated_at: "t",
            pre_version: None,
            post_version: "v0001",
            base: &SchemaInfo::default(),
            target: &SchemaInfo::default(),
            declared_intent: None,
        })
        .expect_err("lowered copy_attribute must be rejected");

        assert!(matches!(
            error,
            crate::error::MigrationError::UnsupportedChange { .. }
        ));
    }
}
