//! Type-safe field references for building query expressions.
//!
//! [`FieldRef`] provides typed accessors for building [`Expr`] filters
//! and sort specifications without string-based attribute names.
//!
//! # Example
//!
//! ```ignore
//! // Instead of stringly-typed:
//! Expr::gte("age", AttributeValue::Long(18))
//!
//! // Use type-safe field references:
//! Person::fields().age.gte(Age(18))
//! ```

use std::marker::PhantomData;

use crate::attribute::TypeBridgeAttribute;
use crate::expr::{Agg, Expr, SortDir};

/// A typed reference to an entity/relation attribute field.
///
/// Generated by derive macros as part of `XxxFields` structs.
/// Provides type-safe expression builders that accept the concrete
/// attribute type rather than raw `AttributeValue`.
pub struct FieldRef<A: TypeBridgeAttribute> {
    attr_name: &'static str,
    _marker: PhantomData<A>,
}

impl<A: TypeBridgeAttribute> FieldRef<A> {
    /// Create a new field reference for the given attribute name.
    pub const fn new(attr_name: &'static str) -> Self {
        Self {
            attr_name,
            _marker: PhantomData,
        }
    }

    /// The TypeDB attribute name this field refers to.
    pub const fn attr_name(&self) -> &'static str {
        self.attr_name
    }

    // -- Comparison expressions --

    /// Equality: `attr == value`.
    pub fn eq(&self, value: A) -> Expr {
        Expr::Eq {
            attr: self.attr_name.to_string(),
            value: value.to_value(),
        }
    }

    /// Not equal: `attr != value`.
    pub fn neq(&self, value: A) -> Expr {
        Expr::Neq {
            attr: self.attr_name.to_string(),
            value: value.to_value(),
        }
    }

    /// Greater than: `attr > value`.
    pub fn gt(&self, value: A) -> Expr {
        Expr::Gt {
            attr: self.attr_name.to_string(),
            value: value.to_value(),
        }
    }

    /// Greater than or equal: `attr >= value`.
    pub fn gte(&self, value: A) -> Expr {
        Expr::Gte {
            attr: self.attr_name.to_string(),
            value: value.to_value(),
        }
    }

    /// Less than: `attr < value`.
    pub fn lt(&self, value: A) -> Expr {
        Expr::Lt {
            attr: self.attr_name.to_string(),
            value: value.to_value(),
        }
    }

    /// Less than or equal: `attr <= value`.
    pub fn lte(&self, value: A) -> Expr {
        Expr::Lte {
            attr: self.attr_name.to_string(),
            value: value.to_value(),
        }
    }

    // -- String expressions --

    /// String contains: `attr contains substring`.
    pub fn contains(&self, substring: impl Into<String>) -> Expr {
        Expr::Contains {
            attr: self.attr_name.to_string(),
            substring: substring.into(),
        }
    }

    /// String like (regex): `attr like pattern`.
    pub fn like(&self, pattern: impl Into<String>) -> Expr {
        Expr::Like {
            attr: self.attr_name.to_string(),
            pattern: pattern.into(),
        }
    }

    // -- Sort specifications --

    /// Sort ascending by this field.
    pub fn asc(&self) -> (String, SortDir) {
        (self.attr_name.to_string(), SortDir::Asc)
    }

    /// Sort descending by this field.
    pub fn desc(&self) -> (String, SortDir) {
        (self.attr_name.to_string(), SortDir::Desc)
    }

    // -- Aggregation helpers --

    /// Sum this field's values.
    pub fn sum(&self) -> Agg {
        Agg::Sum(self.attr_name.to_string())
    }

    /// Minimum of this field's values.
    pub fn min(&self) -> Agg {
        Agg::Min(self.attr_name.to_string())
    }

    /// Maximum of this field's values.
    pub fn max(&self) -> Agg {
        Agg::Max(self.attr_name.to_string())
    }

    /// Arithmetic mean of this field's values.
    pub fn mean(&self) -> Agg {
        Agg::Mean(self.attr_name.to_string())
    }

    /// Median of this field's values.
    pub fn median(&self) -> Agg {
        Agg::Median(self.attr_name.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::define_attribute;

    define_attribute!(TestName, "name", "string");
    define_attribute!(TestAge, "age", "long");

    #[test]
    fn field_ref_eq() {
        let field: FieldRef<TestAge> = FieldRef::new("age");
        let expr = field.eq(TestAge(30));
        match expr {
            Expr::Eq { attr, value } => {
                assert_eq!(attr, "age");
                assert_eq!(value, crate::value::AttributeValue::Long(30));
            }
            _ => panic!("expected Eq"),
        }
    }

    #[test]
    fn field_ref_comparisons() {
        let field: FieldRef<TestAge> = FieldRef::new("age");
        assert!(matches!(field.gt(TestAge(1)), Expr::Gt { .. }));
        assert!(matches!(field.lt(TestAge(1)), Expr::Lt { .. }));
        assert!(matches!(field.gte(TestAge(1)), Expr::Gte { .. }));
        assert!(matches!(field.lte(TestAge(1)), Expr::Lte { .. }));
        assert!(matches!(field.neq(TestAge(1)), Expr::Neq { .. }));
    }

    #[test]
    fn field_ref_string_ops() {
        let field: FieldRef<TestName> = FieldRef::new("name");
        assert!(matches!(field.contains("Ali"), Expr::Contains { .. }));
        assert!(matches!(field.like("^A.*"), Expr::Like { .. }));
    }

    #[test]
    fn field_ref_sort() {
        let field: FieldRef<TestAge> = FieldRef::new("age");
        let (attr, dir) = field.asc();
        assert_eq!(attr, "age");
        assert_eq!(dir, SortDir::Asc);
        let (_, dir) = field.desc();
        assert_eq!(dir, SortDir::Desc);
    }

    #[test]
    fn field_ref_aggregations() {
        let field: FieldRef<TestAge> = FieldRef::new("age");
        assert!(matches!(field.sum(), Agg::Sum(ref a) if a == "age"));
        assert!(matches!(field.min(), Agg::Min(ref a) if a == "age"));
        assert!(matches!(field.max(), Agg::Max(ref a) if a == "age"));
        assert!(matches!(field.mean(), Agg::Mean(ref a) if a == "age"));
        assert!(matches!(field.median(), Agg::Median(ref a) if a == "age"));
    }
}
