"""Offline authoring integration coverage (#166).

Authors checked artifacts with no database connection, then proves they
replay against a real TypeDB, and that the live generator (which delegates
to the same Rust core) produces byte-identical artifacts for identical
inputs.
"""

import re
from pathlib import Path

import pytest

from type_bridge import Entity, Flag, Key, Relation, Role, String, TypeFlags
from type_bridge.attribute import AttributeFlags
from type_bridge.migration import (
    MigrationExecutor,
    MigrationGenerator,
    SchemaIntrospector,
    author_migration,
    without_migration_state_schema,
)
from type_bridge.migration.info import SchemaInfo


class OiName(String):
    flags = AttributeFlags(name="oi-name")


class OiLinkId(String):
    flags = AttributeFlags(name="oi-link-id")


class OiPerson(Entity):
    flags = TypeFlags(name="oi-person")
    name: OiName = Flag(Key)


class OiBadge(Entity):
    flags = TypeFlags(name="oi-badge")
    name: OiName = Flag(Key)


class OiLegacyLink(Relation):
    flags = TypeFlags(name="oi-legacy-link")
    subject: Role[OiPerson] = Role("subject", OiPerson)
    badge: Role[OiBadge] = Role("badge", OiBadge)
    link_id: OiLinkId = Flag(Key)


V1_MODELS = [OiPerson, OiBadge]
V2_MODELS = [OiPerson, OiBadge, OiLegacyLink]


def _schema_info(models) -> dict:
    info = SchemaInfo()
    info.entities = [m for m in models if issubclass(m, Entity)]
    info.relations = [m for m in models if issubclass(m, Relation)]
    info.attribute_classes = {OiName, OiLinkId} if OiLegacyLink in models else {OiName}
    return info.to_rust_schema_info()


@pytest.mark.integration
@pytest.mark.order(335)
def test_offline_authored_artifacts_replay_fresh(clean_db, tmp_path: Path):
    """Artifacts authored with no DB connection apply to a fresh database."""
    migrations_dir = tmp_path / "migrations"

    initial = author_migration(
        SchemaInfo().to_rust_schema_info(),
        _schema_info(V1_MODELS),
        app_label="migrations",
        name="0001_initial",
        snapshot_version="v0001",
        generated_at="2026-07-13T00:00:00+00:00",
    )
    assert initial is not None
    initial.write_to(migrations_dir)

    add_link = author_migration(
        _schema_info(V1_MODELS),
        _schema_info(V2_MODELS),
        app_label="migrations",
        name="0002_add_link",
        dependencies=[("migrations", "0001_initial")],
        snapshot_version="v0002",
        previous_snapshot_version="v0001",
        generated_at="2026-07-13T00:00:00+00:00",
    )
    assert add_link is not None
    add_link.write_to(migrations_dir)

    executor = MigrationExecutor(clean_db, migrations_dir)
    results = executor.migrate()

    assert [result.name for result in results] == ["0001_initial", "0002_add_link"]
    assert all(result.success for result in results)

    schema = SchemaIntrospector(clean_db).introspect()
    assert "oi-person" in schema.get_entity_names()
    assert "oi-legacy-link" in schema.get_relation_names()


@pytest.mark.integration
@pytest.mark.order(336)
def test_live_and_offline_authoring_produce_identical_artifacts(clean_db, tmp_path: Path):
    """Live makemigrations and offline authoring share one canonical core."""
    live_dir = tmp_path / "live" / "migrations"
    generator = MigrationGenerator(clean_db, live_dir)
    executor = MigrationExecutor(clean_db, live_dir)
    assert generator.generate(models=V1_MODELS, name="initial") is not None
    assert all(result.success for result in executor.migrate())

    live_path = generator.generate(models=V2_MODELS, name="add_link")
    assert live_path is not None
    live_source = live_path.read_text()
    timestamp_match = re.search(r"Auto-generated by type_bridge on (.+)$", live_source, re.M)
    assert timestamp_match is not None

    base = without_migration_state_schema(
        SchemaIntrospector(clean_db).introspect()
    ).to_rust_schema_info()
    offline = author_migration(
        base,
        _schema_info(V2_MODELS),
        app_label="migrations",
        name="0002_add_link",
        dependencies=[("migrations", "0001_initial")],
        snapshot_version="v0002",
        previous_snapshot_version="v0001",
        generated_at=timestamp_match.group(1),
    )
    assert offline is not None

    assert offline.python_source == live_source
    live_sidecar = live_path.with_suffix(".json").read_bytes()
    offline_files = dict(offline.files)
    assert offline_files["0002_add_link.json"] == live_sidecar
    for relative_path, contents in offline.files:
        if relative_path.startswith("snapshots/v0002/"):
            assert (live_dir / relative_path).read_bytes() == contents, relative_path
