[workspace]
resolver = "3"
members = [
    "crates/contract",
    "crates/core",
    "crates/migration",
    "crates/python",
    "crates/server",
    "crates/typedb-runtime",
    "crates/orm",
    "crates/orm-derive",
    "crates/node",
    "crates/toml-transpiler",
    "vendor/typedb-protocol-b7",
    "vendor/typedb-driver-b7",
    "vendor/typedb-protocol-b9",
    "vendor/typedb-driver-b9",
]

[workspace.package]
license = "MIT"
repository = "https://github.com/ds1sqe/type-bridge"
authors = ["ds1sqe"]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)', 'cfg(coverage)'] }
