"""Type stubs for the ``type_bridge_core`` Rust extension module.

Hand-maintained to mirror the PyO3 bindings in
``crates/python/src/lib.rs`` (and ``transpiler.rs``). Shipped with the package
(``py.typed``) so downstream consumers and this repo share one source of type
truth for the extension. Only the symbols imported directly by Python source
carry precise signatures; the remaining extension classes and functions are
reached dynamically and stay visible through the module-level ``__getattr__``
fallback rather than being enumerated here.

``TypeSchema``'s ``entities`` / ``relations`` / ``attributes`` / ``functions`` /
``structs`` are PyO3 ``#[getter]`` properties, so they are declared with
``@property``; declaring them as plain methods makes type checkers reject
``schema.attributes[...]`` and ``"x" in schema.attributes``.
"""

from collections.abc import Mapping
from typing import Any

class ValueCoercer:
    def __init__(self) -> None: ...
    def coerce(self, value: Any, target_type: str) -> Any: ...
    def coerce_batch(self, pairs: list[tuple[Any, str]]) -> Any: ...
    def format_typeql(self, value: Any, value_type: str) -> str: ...

class QueryCompiler:
    def __init__(self) -> None: ...
    def compile(self, clauses: list[Any]) -> str: ...
    def compile_dicts(self, clauses: list[Any]) -> str: ...
    def parse(self, input: str) -> Any: ...

class TypeSchema:
    @staticmethod
    def from_typeql(input: str) -> TypeSchema: ...
    @staticmethod
    def from_json(json: str) -> TypeSchema: ...
    def to_json(self) -> str: ...
    def is_abstract(self, type_name: str) -> bool: ...
    def get_all_owned_attributes(self, name: str) -> list[Any]: ...
    def get_all_plays_roles(self, name: str) -> list[Any]: ...
    def get_all_relates(self, name: str) -> list[Any]: ...
    def validate_query(self, clauses: list[Any]) -> Any: ...
    @property
    def entities(self) -> Mapping[str, Any]: ...
    @property
    def relations(self) -> Mapping[str, Any]: ...
    @property
    def attributes(self) -> Mapping[str, Any]: ...
    @property
    def functions(self) -> Mapping[str, Any]: ...
    @property
    def structs(self) -> Mapping[str, Any]: ...

class ValidationEngine:
    def __init__(self) -> None: ...
    def validate_type_name(self, name: str, context: str) -> bool: ...
    def validate_variable_name(self, name: str, context: str) -> bool: ...
    def validate_pattern(self, pattern: Any) -> bool: ...
    def validate_statement(self, statement: Any) -> bool: ...
    def validate_query(self, clauses: list[Any], schema: TypeSchema) -> Any: ...
    def add_rule(self, rule_dict: Any) -> None: ...
    def load_rules(self, json_str: str) -> list[str]: ...
    def export_rules(self) -> str: ...
    def clear_rules(self) -> None: ...
    def rule_count(self) -> int: ...
    def validate_entity(self, entity_data: Any, schema: TypeSchema | None = ...) -> Any: ...

def coerce_value(value: Any, target_type: str) -> Any: ...
def format_value(value: Any) -> str: ...
def parse_typeql_query(input: str) -> Any: ...
def toml_to_typeql(toml_text: str) -> str: ...

# Version gate — SSOT in crates/core/src/version.rs, re-exported here.
class VersionError(Exception):
    """Raised for TypeDB version window violations, band mismatches, probe failures, or parse errors."""

    ...

def min_supported_version() -> str:
    """Return the minimum supported TypeDB version as ``"3.8.0"``."""
    ...

def max_supported_line() -> str:
    """Return the maximum supported TypeDB line as ``"major.minor"`` (e.g. ``"3.11"``)."""
    ...

def band(version: str) -> int | None:
    """Return the protocol band for a TypeDB version string, or ``None`` if unmapped.

    Raises ``VersionError`` when the version string cannot be parsed.
    """
    ...

def check_supported(driver: str, server: str) -> None:
    """Assert that driver and server versions are compatible (window + band).

    Raises ``VersionError`` on window violations or band mismatches.
    """
    ...

def embedded_driver_version() -> str:
    """Return the typedb-driver version compiled into the Rust runtime.

    Returns the band-8 (3.11.x) pin for back-compat. Use
    ``embedded_driver_versions()`` to get all compiled-in bands.
    """
    ...

def embedded_driver_versions() -> dict[int, str]:
    """Return all driver versions compiled into the Rust runtime, keyed by protocol band.

    Returns a dict mapping ``int`` band → ``str`` version for every band
    feature compiled into this build.  The default build returns
    ``{7: "3.8.1", 8: "3.11.5"}``.
    """
    ...

def check_server_supported(server: str) -> None:
    """Assert this build's embedded runtime can serve ``server``.

    Uses band-set membership (not equality): the server passes when its protocol
    band is among the bands compiled into this build.  The band set is derived
    from ``embedded_driver_versions()`` — never a hardcoded literal.

    Raises ``VersionError`` when the server is outside the support window or
    its band is not compiled into this build.
    """
    ...

def server_version(address: str, http_port: int = 8000, tls: bool = False) -> str:
    """Query the TypeDB HTTP API for the server version.

    Returns the detected version as a string (e.g. ``"3.10.4"``).
    Raises ``VersionError`` when the endpoint is unreachable or the response
    cannot be parsed.
    """
    ...

class PyRustDatabase:
    """Rust-backed TypeDB database connection."""

    @staticmethod
    def connect(
        address: str,
        database: str,
        username: str | None = ...,
        password: str | None = ...,
        http_port: int = 8000,
        server_version: str | None = ...,
    ) -> PyRustDatabase: ...
    def __getattr__(self, name: str) -> Any: ...

def __getattr__(name: str) -> Any: ...
