[package]
name = "type-bridge-query"
version = "1.5.11"
edition = "2024"
publish = false
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
type-bridge-contract = { path = "../contract", version = "1.5.11" }
type-bridge-schema = { path = "../schema", version = "1.5.11" }

[lints]
workspace = true
