[package]
name = "type-bridge-query"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
type-bridge-contract = { path = "../contract", version = "0.1.0" }
type-bridge-schema = { path = "../schema", version = "0.1.0" }

[lints]
workspace = true
