//! Code generator: TypeQL schema → Rust source files.
//!
//! Parses a TypeQL `define` block using `type_bridge_core_lib::TypeSchema`
//! and generates Rust source files with derive macros.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write;

use type_bridge_core_lib::schema::{Cardinality, EntityType, OwnedAttribute, RelationType, TypeSchema};

use super::naming::{to_pascal_case, to_snake_case};

/// Generated Rust model source files.
#[derive(Debug, Clone)]
pub struct GeneratedModels {
    /// `mod.rs` with re-exports.
    pub mod_rs: String,
    /// `attributes.rs` with `define_attribute!` invocations.
    pub attributes_rs: String,
    /// `entities.rs` with entity struct definitions.
    pub entities_rs: String,
    /// `relations.rs` with relation struct definitions.
    pub relations_rs: String,
}

/// Parse TypeQL and generate Rust model source code.
pub fn generate_from_typeql(input: &str) -> Result<GeneratedModels, String> {
    let schema = TypeSchema::from_typeql(input).map_err(|e| e.to_string())?;
    Ok(generate_rust_models(&schema))
}

/// Generate Rust model source from a resolved `TypeSchema`.
pub fn generate_rust_models(schema: &TypeSchema) -> GeneratedModels {
    let attributes_rs = generate_attributes(schema);
    let entities_rs = generate_entities(schema);
    let relations_rs = generate_relations(schema);
    let mod_rs = generate_mod_rs();

    GeneratedModels {
        mod_rs,
        attributes_rs,
        entities_rs,
        relations_rs,
    }
}

/// Map TypeDB value type string to the Rust `define_attribute!` value type name.
fn value_type_to_rust(vt: &str) -> &str {
    match vt {
        "string" => "string",
        "long" => "long",
        "double" => "double",
        "boolean" => "boolean",
        "date" => "date",
        "datetime" => "datetime",
        "datetime-tz" => "datetime-tz",
        "decimal" => "decimal",
        "duration" => "duration",
        other => other,
    }
}

// ---------------------------------------------------------------------------
// Attributes
// ---------------------------------------------------------------------------

fn generate_attributes(schema: &TypeSchema) -> String {
    let mut out = String::new();
    writeln!(out, "//! Generated attribute types.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Auto-generated by type-bridge codegen. Do not edit manually.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use type_bridge_orm::define_attribute;").unwrap();
    writeln!(out).unwrap();

    for attr in schema.attributes.values() {
        // Skip abstract attribute types — they have no concrete value type
        if attr.is_abstract {
            continue;
        }
        let struct_name = to_pascal_case(&attr.name);
        let vt = value_type_to_rust(&attr.value_type);
        writeln!(
            out,
            "define_attribute!({}, \"{}\", \"{}\");",
            struct_name, attr.name, vt
        )
        .unwrap();
    }

    out
}

// ---------------------------------------------------------------------------
// Entities
// ---------------------------------------------------------------------------

fn generate_entities(schema: &TypeSchema) -> String {
    let mut out = String::new();
    writeln!(out, "//! Generated entity types.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Auto-generated by type-bridge codegen. Do not edit manually.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use type_bridge_orm::{{DeriveEntity, Result}};").unwrap();
    writeln!(out, "use super::attributes::*;").unwrap();
    writeln!(out).unwrap();

    // Topologically sort entities: parents before children
    let order = topological_sort(&schema.entities, |e| e.parent.as_deref());

    for name in &order {
        let entity = &schema.entities[name.as_str()];
        generate_entity(&mut out, entity, schema);
        writeln!(out).unwrap();
    }

    out
}

fn generate_entity(out: &mut String, entity: &EntityType, schema: &TypeSchema) {
    // Build #[entity(...)] attribute
    let mut entity_attr_parts = vec![format!("name = \"{}\"", entity.name)];
    if entity.is_abstract {
        entity_attr_parts.push("r#abstract".to_string());
    }
    if let Some(ref parent) = entity.parent {
        entity_attr_parts.push(format!("extends = \"{}\"", parent));
    }

    let struct_name = to_pascal_case(&entity.name);

    writeln!(out, "#[derive(DeriveEntity, Debug)]").unwrap();
    writeln!(out, "#[entity({})]", entity_attr_parts.join(", ")).unwrap();
    writeln!(out, "pub struct {} {{", struct_name).unwrap();
    writeln!(out, "    pub iid: Option<String>,").unwrap();

    // Use owns_order for deterministic field ordering
    let attr_names = if entity.owns_order.is_empty() {
        entity.owns.iter().map(|o| o.name.as_str()).collect::<Vec<_>>()
    } else {
        entity.owns_order.iter().map(|s| s.as_str()).collect()
    };

    // Build a lookup map from owned attributes
    let owns_map: BTreeMap<&str, &OwnedAttribute> =
        entity.owns.iter().map(|o| (o.name.as_str(), o)).collect();

    for attr_name in &attr_names {
        if let Some(own) = owns_map.get(attr_name) {
            let field_name = to_snake_case(attr_name);
            let attr_type = to_pascal_case(attr_name);

            // Determine field annotations
            let mut field_attrs = Vec::new();
            if own.is_key {
                field_attrs.push("key".to_string());
            }
            if own.is_unique {
                field_attrs.push("unique".to_string());
            }
            if let Some(ref card) = own.cardinality {
                field_attrs.push(format!("card_min = {}", card.min));
                if let Some(max) = card.max {
                    field_attrs.push(format!("card_max = {}", max));
                }
            }

            let field_attr_line = if field_attrs.is_empty() {
                String::new()
            } else {
                format!("    #[field({})]\n", field_attrs.join(", "))
            };

            // Determine if field should be Option<T> or Vec<T>
            let field_type = determine_field_type(&attr_type, own, schema);

            write!(out, "{}", field_attr_line).unwrap();
            writeln!(out, "    pub {}: {},", field_name, field_type).unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
}

/// Determine the Rust field type based on cardinality.
fn determine_field_type(attr_type: &str, own: &OwnedAttribute, _schema: &TypeSchema) -> String {
    match &own.cardinality {
        Some(Cardinality { min: 0, max: Some(1) }) => format!("Option<{}>", attr_type),
        Some(Cardinality { max: None, .. }) => format!("Vec<{}>", attr_type),
        Some(Cardinality { max: Some(max), .. }) if *max > 1 => format!("Vec<{}>", attr_type),
        _ => attr_type.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

fn generate_relations(schema: &TypeSchema) -> String {
    let mut out = String::new();
    writeln!(out, "//! Generated relation types.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Auto-generated by type-bridge codegen. Do not edit manually.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use type_bridge_orm::{{DeriveRelation, RolePlayerRef, Result}};").unwrap();
    writeln!(out, "use super::attributes::*;").unwrap();
    writeln!(out).unwrap();

    // Topologically sort relations: parents before children
    let order = topological_sort(&schema.relations, |r| r.parent.as_deref());

    for name in &order {
        let relation = &schema.relations[name.as_str()];
        generate_relation(&mut out, relation, schema);
        writeln!(out).unwrap();
    }

    out
}

fn generate_relation(out: &mut String, relation: &RelationType, schema: &TypeSchema) {
    // Build #[relation(...)] attribute
    let mut rel_attr_parts = vec![format!("name = \"{}\"", relation.name)];
    if relation.is_abstract {
        rel_attr_parts.push("r#abstract".to_string());
    }
    if let Some(ref parent) = relation.parent {
        rel_attr_parts.push(format!("extends = \"{}\"", parent));
    }

    let struct_name = to_pascal_case(&relation.name);

    writeln!(out, "#[derive(DeriveRelation, Debug)]").unwrap();
    writeln!(out, "#[relation({})]", rel_attr_parts.join(", ")).unwrap();
    writeln!(out, "pub struct {} {{", struct_name).unwrap();
    writeln!(out, "    pub iid: Option<String>,").unwrap();

    // Role fields — resolve player types from entity/relation plays
    let mut seen_roles: HashSet<String> = HashSet::new();
    for role in &relation.roles {
        let player_type = resolve_role_player(schema, &relation.name, &role.name);
        let field_name = make_unique_role_field(&role.name, &mut seen_roles);
        writeln!(
            out,
            "    #[role(name = \"{}\", player_type = \"{}\")]",
            role.name, player_type
        )
        .unwrap();
        writeln!(out, "    pub {}: RolePlayerRef,", field_name).unwrap();
    }

    // Attribute fields
    let attr_names = if relation.owns_order.is_empty() {
        relation.owns.iter().map(|o| o.name.as_str()).collect::<Vec<_>>()
    } else {
        relation.owns_order.iter().map(|s| s.as_str()).collect()
    };

    let owns_map: BTreeMap<&str, &OwnedAttribute> =
        relation.owns.iter().map(|o| (o.name.as_str(), o)).collect();

    for attr_name in &attr_names {
        if let Some(own) = owns_map.get(attr_name) {
            let field_name = to_snake_case(attr_name);
            let attr_type = to_pascal_case(attr_name);

            let mut field_attrs = Vec::new();
            if own.is_key {
                field_attrs.push("key".to_string());
            }
            if own.is_unique {
                field_attrs.push("unique".to_string());
            }
            if let Some(ref card) = own.cardinality {
                field_attrs.push(format!("card_min = {}", card.min));
                if let Some(max) = card.max {
                    field_attrs.push(format!("card_max = {}", max));
                }
            }

            let field_attr_line = if field_attrs.is_empty() {
                String::new()
            } else {
                format!("    #[field({})]\n", field_attrs.join(", "))
            };

            let field_type = determine_field_type(&attr_type, own, schema);

            write!(out, "{}", field_attr_line).unwrap();
            writeln!(out, "    pub {}: Option<{}>,", field_name, field_type).unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
}

/// Resolve which entity plays a given role in a relation.
///
/// Searches all entities' `plays` lists for a matching `relation:role` reference.
fn resolve_role_player(schema: &TypeSchema, relation_name: &str, role_name: &str) -> String {
    let role_ref = format!("{}:{}", relation_name, role_name);

    // Search entities
    for entity in schema.entities.values() {
        for play in &entity.plays {
            if play.role_ref == role_ref {
                return entity.name.clone();
            }
        }
    }

    // Search relations (relations can play roles too)
    for rel in schema.relations.values() {
        for play in &rel.plays {
            if play.role_ref == role_ref {
                return rel.name.clone();
            }
        }
    }

    "unknown".to_string()
}

/// Make a unique field name for duplicate role names (e.g., friendship has two "friend" roles).
fn make_unique_role_field(role_name: &str, seen: &mut HashSet<String>) -> String {
    let base = to_snake_case(role_name);
    if seen.insert(base.clone()) {
        return base;
    }
    // Append numeric suffix
    let mut i = 1;
    loop {
        let candidate = format!("{}_{}", base, i);
        if seen.insert(candidate.clone()) {
            return candidate;
        }
        i += 1;
    }
}

// ---------------------------------------------------------------------------
// mod.rs
// ---------------------------------------------------------------------------

fn generate_mod_rs() -> String {
    let mut out = String::new();
    writeln!(out, "//! Generated models.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Auto-generated by type-bridge codegen. Do not edit manually.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub mod attributes;").unwrap();
    writeln!(out, "pub mod entities;").unwrap();
    writeln!(out, "pub mod relations;").unwrap();
    out
}

// ---------------------------------------------------------------------------
// Topological sort
// ---------------------------------------------------------------------------

fn topological_sort<T, F>(map: &BTreeMap<String, T>, get_parent: F) -> Vec<String>
where
    F: Fn(&T) -> Option<&str>,
{
    let mut result = Vec::new();
    let mut visited = HashSet::new();

    fn visit<T2, F2>(
        name: &str,
        map: &BTreeMap<String, T2>,
        get_parent: &F2,
        visited: &mut HashSet<String>,
        result: &mut Vec<String>,
    ) where
        F2: Fn(&T2) -> Option<&str>,
    {
        if visited.contains(name) {
            return;
        }
        visited.insert(name.to_string());
        if let Some(entry) = map.get(name)
            && let Some(parent) = get_parent(entry)
        {
            visit(parent, map, get_parent, visited, result);
        }
        result.push(name.to_string());
    }

    for name in map.keys() {
        visit(name, map, &get_parent, &mut visited, &mut result);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn basic_schema_tql() -> &'static str {
        "define\nattribute name, value string;\nattribute age, value long;\nentity person, owns name @key, owns age, plays employment:employee;"
    }

    fn inheritance_schema_tql() -> &'static str {
        "define\nattribute name, value string;\nattribute breed, value string;\nentity animal @abstract, owns name @key;\nentity dog sub animal, owns breed, plays ownership:pet;"
    }

    fn relation_schema_tql() -> &'static str {
        "define\nattribute name, value string;\nattribute position, value string;\nentity person, owns name @key, plays employment:employee;\nentity company, owns name @key, plays employment:employer;\nrelation employment, relates employee, relates employer, owns position;"
    }

    #[test]
    fn generate_basic_attributes() {
        let models = generate_from_typeql(basic_schema_tql()).unwrap();
        assert!(models.attributes_rs.contains("define_attribute!(Age, \"age\", \"long\");"));
        assert!(models.attributes_rs.contains("define_attribute!(Name, \"name\", \"string\");"));
    }

    #[test]
    fn generate_basic_entity() {
        let models = generate_from_typeql(basic_schema_tql()).unwrap();
        assert!(
            models.entities_rs.contains("#[entity(name = \"person\")]"),
            "entity attr missing: {}",
            models.entities_rs
        );
        assert!(
            models.entities_rs.contains("pub struct Person"),
            "struct missing: {}",
            models.entities_rs
        );
        assert!(
            models.entities_rs.contains("#[field(key)]"),
            "key annotation missing: {}",
            models.entities_rs
        );
    }

    #[test]
    fn generate_abstract_and_inheritance() {
        let models = generate_from_typeql(inheritance_schema_tql()).unwrap();

        // Animal should be abstract
        assert!(
            models.entities_rs.contains("r#abstract"),
            "abstract missing: {}",
            models.entities_rs
        );
        // Dog should extend animal
        assert!(
            models.entities_rs.contains("extends = \"animal\""),
            "extends missing: {}",
            models.entities_rs
        );
        // Animal should appear before Dog (topological order)
        let animal_pos = models.entities_rs.find("struct Animal").unwrap();
        let dog_pos = models.entities_rs.find("struct Dog").unwrap();
        assert!(
            animal_pos < dog_pos,
            "Animal should come before Dog: {}",
            models.entities_rs
        );
    }

    #[test]
    fn generate_relation_with_roles() {
        let models = generate_from_typeql(relation_schema_tql()).unwrap();

        assert!(
            models.relations_rs.contains("#[relation(name = \"employment\")]"),
            "relation attr missing: {}",
            models.relations_rs
        );
        assert!(
            models.relations_rs.contains("pub struct Employment"),
            "struct missing: {}",
            models.relations_rs
        );
        // Role player resolution
        assert!(
            models.relations_rs.contains("player_type = \"person\""),
            "employee role missing: {}",
            models.relations_rs
        );
        assert!(
            models.relations_rs.contains("player_type = \"company\""),
            "employer role missing: {}",
            models.relations_rs
        );
    }

    #[test]
    fn generate_mod_rs_has_re_exports() {
        let models = generate_from_typeql(basic_schema_tql()).unwrap();
        assert!(models.mod_rs.contains("pub mod attributes;"));
        assert!(models.mod_rs.contains("pub mod entities;"));
        assert!(models.mod_rs.contains("pub mod relations;"));
    }

    #[test]
    fn generate_optional_field() {
        let tql = "define\nattribute name, value string;\nattribute nickname, value string;\nentity person, owns name @key, owns nickname @card(0..1);";
        let models = generate_from_typeql(tql).unwrap();
        assert!(
            models.entities_rs.contains("Option<Nickname>"),
            "optional field missing: {}",
            models.entities_rs
        );
    }

    #[test]
    fn generate_multi_value_field() {
        let tql = "define\nattribute name, value string;\nattribute tag, value string;\nentity person, owns name @key, owns tag @card(0..);";
        let models = generate_from_typeql(tql).unwrap();
        assert!(
            models.entities_rs.contains("Vec<Tag>"),
            "multi-value field missing: {}",
            models.entities_rs
        );
    }

    #[test]
    fn generate_skips_abstract_attributes() {
        let tql = "define\nattribute content @abstract, value string;\nattribute name sub content, value string;\nentity person, owns name @key;";
        let models = generate_from_typeql(tql).unwrap();
        // Abstract attribute should not generate define_attribute!
        assert!(
            !models.attributes_rs.contains("define_attribute!(Content"),
            "abstract attr should be skipped: {}",
            models.attributes_rs
        );
        // Concrete child should still be generated
        assert!(
            models.attributes_rs.contains("define_attribute!(Name"),
            "concrete attr should be generated: {}",
            models.attributes_rs
        );
    }

    #[test]
    fn duplicate_role_names_get_suffixed() {
        let tql = "define\nattribute name, value string;\nentity person, owns name @key, plays friendship:friend;\nrelation friendship, relates friend;";
        let models = generate_from_typeql(tql).unwrap();
        assert!(
            models.relations_rs.contains("pub struct Friendship"),
            "struct missing: {}",
            models.relations_rs
        );
    }
}
