//! Owned, source-free runtime catalog over a verified history bundle.

use type_bridge_contract::diagnostic::Diagnostic;
use type_bridge_contract::fingerprint::Fingerprint;
use type_bridge_contract::migration::MigrationId;
use type_bridge_schema::ManagedDeltaContext;

use crate::{
    MigrationHistoryGraph, VerifiedMigrationHistoryBundle, VerifiedMigrationHistoryBundleEntry,
    decode_verified_migration_history_bundle,
};

/// Immutable runtime migration catalog admitted from canonical generated bytes.
#[derive(Clone, Debug)]
pub struct MigrationCatalog {
    bundle: VerifiedMigrationHistoryBundle,
    graph: MigrationHistoryGraph,
}

impl MigrationCatalog {
    /// Decode, replay, and open one generated canonical history bundle.
    pub fn open(bytes: &[u8], context: &ManagedDeltaContext) -> Result<Self, Diagnostic> {
        Self::from_verified_bundle(decode_verified_migration_history_bundle(bytes, context)?)
    }

    /// Open one already verified immutable bundle.
    pub fn from_verified_bundle(
        bundle: VerifiedMigrationHistoryBundle,
    ) -> Result<Self, Diagnostic> {
        let graph = bundle.history_graph()?;
        Ok(Self { bundle, graph })
    }

    /// Return the exact canonical bundle content identity.
    pub const fn fingerprint(&self) -> &Fingerprint {
        self.bundle.fingerprint()
    }

    /// Return history entries in deterministic topological order.
    pub fn entries(&self) -> &[VerifiedMigrationHistoryBundleEntry] {
        self.bundle.entries()
    }

    /// Return canonical graph heads.
    pub fn heads(&self) -> &[MigrationId] {
        self.bundle.heads()
    }

    /// Borrow the replay-verified graph used by preview and execution planning.
    pub const fn graph(&self) -> &MigrationHistoryGraph {
        &self.graph
    }

    /// Borrow the complete verified bundle authority.
    pub const fn bundle(&self) -> &VerifiedMigrationHistoryBundle {
        &self.bundle
    }
}
