#pragma once

#include <typebridge/type_bridge_abi_1_4.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TYPE_BRIDGE_MIGRATION_EXECUTION_OPTIONS_V1 1u
#define TYPE_BRIDGE_MIGRATION_EXECUTION_HAS_TIMEOUT 1u
#define TYPE_BRIDGE_MIGRATION_DIGEST_LENGTH 32u

typedef int32_t type_bridge_database_pair_state_t;
#define TYPE_BRIDGE_DATABASE_PAIR_ABSENT ((type_bridge_database_pair_state_t)1)
#define TYPE_BRIDGE_DATABASE_PAIR_STANDALONE_MANAGED ((type_bridge_database_pair_state_t)2)
#define TYPE_BRIDGE_DATABASE_PAIR_OWNED ((type_bridge_database_pair_state_t)3)
#define TYPE_BRIDGE_DATABASE_PAIR_OWNED_JOURNAL_ORPHAN ((type_bridge_database_pair_state_t)4)
typedef int32_t type_bridge_database_create_outcome_t;
#define TYPE_BRIDGE_DATABASE_CREATE_CREATED ((type_bridge_database_create_outcome_t)1)
#define TYPE_BRIDGE_DATABASE_CREATE_ALREADY_EXISTS ((type_bridge_database_create_outcome_t)2)
typedef int32_t type_bridge_database_delete_outcome_t;
#define TYPE_BRIDGE_DATABASE_DELETE_ALREADY_ABSENT ((type_bridge_database_delete_outcome_t)1)
#define TYPE_BRIDGE_DATABASE_DELETE_STANDALONE_MANAGED ((type_bridge_database_delete_outcome_t)2)
#define TYPE_BRIDGE_DATABASE_DELETE_OWNED_PAIR ((type_bridge_database_delete_outcome_t)3)
#define TYPE_BRIDGE_DATABASE_DELETE_OWNED_JOURNAL_ORPHAN ((type_bridge_database_delete_outcome_t)4)
typedef int32_t type_bridge_migration_safety_t;
#define TYPE_BRIDGE_MIGRATION_SAFETY_FORMAL_ONLY ((type_bridge_migration_safety_t)1)
#define TYPE_BRIDGE_MIGRATION_SAFETY_SCHEMA_METADATA ((type_bridge_migration_safety_t)2)
#define TYPE_BRIDGE_MIGRATION_SAFETY_ADDITIVE ((type_bridge_migration_safety_t)3)
#define TYPE_BRIDGE_MIGRATION_SAFETY_CONDITIONAL ((type_bridge_migration_safety_t)4)
#define TYPE_BRIDGE_MIGRATION_SAFETY_BACKFILL_REQUIRED ((type_bridge_migration_safety_t)5)
#define TYPE_BRIDGE_MIGRATION_SAFETY_DESTRUCTIVE ((type_bridge_migration_safety_t)6)
#define TYPE_BRIDGE_MIGRATION_SAFETY_OPAQUE ((type_bridge_migration_safety_t)7)
#define TYPE_BRIDGE_MIGRATION_SAFETY_UNSUPPORTED ((type_bridge_migration_safety_t)8)
typedef int32_t type_bridge_migration_direction_t;
#define TYPE_BRIDGE_MIGRATION_DIRECTION_APPLY ((type_bridge_migration_direction_t)1)
#define TYPE_BRIDGE_MIGRATION_DIRECTION_ROLLBACK ((type_bridge_migration_direction_t)2)
typedef int32_t type_bridge_migration_execution_status_t;
#define TYPE_BRIDGE_MIGRATION_EXECUTION_APPLIED ((type_bridge_migration_execution_status_t)1)
#define TYPE_BRIDGE_MIGRATION_EXECUTION_ROLLED_BACK ((type_bridge_migration_execution_status_t)2)
#define TYPE_BRIDGE_MIGRATION_EXECUTION_RETRY_SAFE ((type_bridge_migration_execution_status_t)3)
#define TYPE_BRIDGE_MIGRATION_EXECUTION_REQUIRES_RECOVERY ((type_bridge_migration_execution_status_t)4)
typedef int32_t type_bridge_migration_position_kind_t;
#define TYPE_BRIDGE_MIGRATION_POSITION_NONE ((type_bridge_migration_position_kind_t)0)
#define TYPE_BRIDGE_MIGRATION_POSITION_TRANSACTION_GROUP ((type_bridge_migration_position_kind_t)1)
#define TYPE_BRIDGE_MIGRATION_POSITION_BACKFILL_STEP ((type_bridge_migration_position_kind_t)2)
#define TYPE_BRIDGE_MIGRATION_POSITION_MANIFEST_CHECKPOINT ((type_bridge_migration_position_kind_t)3)
#define TYPE_BRIDGE_MIGRATION_POSITION_ROLLBACK_STEP ((type_bridge_migration_position_kind_t)4)
typedef int32_t type_bridge_migration_backfill_direction_t;
#define TYPE_BRIDGE_MIGRATION_BACKFILL_FORWARD ((type_bridge_migration_backfill_direction_t)1)
#define TYPE_BRIDGE_MIGRATION_BACKFILL_REVERSE ((type_bridge_migration_backfill_direction_t)2)
typedef int32_t type_bridge_migration_verification_finding_kind_t;
#define TYPE_BRIDGE_MIGRATION_FINDING_APPLIED_LEDGER ((type_bridge_migration_verification_finding_kind_t)1)
#define TYPE_BRIDGE_MIGRATION_FINDING_LIVE_SEMANTICS ((type_bridge_migration_verification_finding_kind_t)2)
#define TYPE_BRIDGE_MIGRATION_FINDING_DESIRED_DIVERGENCE ((type_bridge_migration_verification_finding_kind_t)3)
#define TYPE_BRIDGE_MIGRATION_FINDING_PENDING_MIGRATIONS ((type_bridge_migration_verification_finding_kind_t)4)
#define TYPE_BRIDGE_MIGRATION_FINDING_CAPABILITIES ((type_bridge_migration_verification_finding_kind_t)5)

typedef struct type_bridge_database_administration type_bridge_database_administration_t;
typedef struct type_bridge_database_deletion_plan type_bridge_database_deletion_plan_t;
typedef struct type_bridge_migration_catalog type_bridge_migration_catalog_t;
typedef struct type_bridge_migration_history_entry type_bridge_migration_history_entry_t;
typedef struct type_bridge_migration_identity type_bridge_migration_identity_t;
typedef struct type_bridge_migration_plan type_bridge_migration_plan_t;
typedef struct type_bridge_migration_plan_entry type_bridge_migration_plan_entry_t;
typedef struct type_bridge_migration_approval_builder type_bridge_migration_approval_builder_t;
typedef struct type_bridge_migration_approval_set type_bridge_migration_approval_set_t;
typedef struct type_bridge_migration_execution_outcome type_bridge_migration_execution_outcome_t;
typedef struct type_bridge_migration_cancellation type_bridge_migration_cancellation_t;
typedef struct type_bridge_migration_backfill_observation type_bridge_migration_backfill_observation_t;
typedef struct type_bridge_migration_verification_report type_bridge_migration_verification_report_t;
typedef struct type_bridge_migration_verification_finding type_bridge_migration_verification_finding_t;

typedef struct type_bridge_migration_execution_options_v1 {
  uint64_t struct_size;
  uint32_t version;
  uint32_t flags;
  uint64_t timeout_milliseconds;
  uint64_t max_transaction_groups;
  uint64_t max_backfill_observations;
  const type_bridge_migration_cancellation_t *cancellation;
} type_bridge_migration_execution_options_v1_t;

type_bridge_status_t type_bridge_database_administration_open(const type_bridge_database_t *, type_bridge_database_administration_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_exists(const type_bridge_database_administration_t *, uint8_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_exists_with_options(const type_bridge_database_administration_t *, const type_bridge_migration_execution_options_v1_t *, uint8_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_create(const type_bridge_database_administration_t *, uint32_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_create_with_options(const type_bridge_database_administration_t *, const type_bridge_migration_execution_options_v1_t *, uint32_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_inspect(const type_bridge_database_administration_t *, uint32_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_inspect_with_options(const type_bridge_database_administration_t *, const type_bridge_migration_execution_options_v1_t *, uint32_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_plan_delete(const type_bridge_database_administration_t *, type_bridge_database_deletion_plan_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_administration_plan_delete_with_options(const type_bridge_database_administration_t *, const type_bridge_migration_execution_options_v1_t *, type_bridge_database_deletion_plan_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_deletion_plan_inspected_state(const type_bridge_database_deletion_plan_t *, uint32_t *);
type_bridge_status_t type_bridge_database_deletion_plan_execute(type_bridge_database_deletion_plan_t *, uint32_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_deletion_plan_execute_with_options(type_bridge_database_deletion_plan_t *, const type_bridge_migration_execution_options_v1_t *, uint32_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_database_deletion_plan_close(type_bridge_database_deletion_plan_t **);
type_bridge_status_t type_bridge_database_administration_close(type_bridge_database_administration_t **);
type_bridge_status_t type_bridge_migration_catalog_open(const type_bridge_schema_package_t *, type_bridge_byte_view_t, type_bridge_migration_catalog_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_catalog_fingerprint(const type_bridge_migration_catalog_t *, type_bridge_byte_view_t *);
type_bridge_status_t type_bridge_migration_catalog_count(const type_bridge_migration_catalog_t *, size_t *);
type_bridge_status_t type_bridge_migration_catalog_entry_at(const type_bridge_migration_catalog_t *, size_t, type_bridge_migration_history_entry_t **);
type_bridge_status_t type_bridge_migration_catalog_head_count(const type_bridge_migration_catalog_t *, size_t *);
type_bridge_status_t type_bridge_migration_catalog_head_at(const type_bridge_migration_catalog_t *, size_t, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_catalog_close(type_bridge_migration_catalog_t **);
type_bridge_status_t type_bridge_migration_history_entry_identity(const type_bridge_migration_history_entry_t *, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_history_entry_parent_count(const type_bridge_migration_history_entry_t *, size_t *);
type_bridge_status_t type_bridge_migration_history_entry_parent_at(const type_bridge_migration_history_entry_t *, size_t, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_history_entry_manifest_digest(const type_bridge_migration_history_entry_t *, uint8_t *, size_t);
type_bridge_status_t type_bridge_migration_history_entry_step_count(const type_bridge_migration_history_entry_t *, size_t *);
type_bridge_status_t type_bridge_migration_history_entry_safety(const type_bridge_migration_history_entry_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_history_entry_reversible(const type_bridge_migration_history_entry_t *, uint8_t *);
type_bridge_status_t type_bridge_migration_history_entry_close(type_bridge_migration_history_entry_t **);
type_bridge_status_t type_bridge_migration_identity_app_label(const type_bridge_migration_identity_t *, type_bridge_byte_view_t *);
type_bridge_status_t type_bridge_migration_identity_name(const type_bridge_migration_identity_t *, type_bridge_byte_view_t *);
type_bridge_status_t type_bridge_migration_identity_new(type_bridge_byte_view_t, type_bridge_byte_view_t, type_bridge_migration_identity_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_identity_close(type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_catalog_preview_apply(const type_bridge_migration_catalog_t *, const type_bridge_migration_identity_t *const *, size_t, const type_bridge_migration_identity_t *const *, size_t, uint8_t, type_bridge_migration_plan_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_catalog_preview_rollback(const type_bridge_migration_catalog_t *, const type_bridge_migration_identity_t *const *, size_t, const type_bridge_migration_identity_t *const *, size_t, type_bridge_migration_plan_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_plan_direction(const type_bridge_migration_plan_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_plan_execution_authorized(const type_bridge_migration_plan_t *, uint8_t *);
type_bridge_status_t type_bridge_migration_plan_count(const type_bridge_migration_plan_t *, size_t *);
type_bridge_status_t type_bridge_migration_plan_entry_at(const type_bridge_migration_plan_t *, size_t, type_bridge_migration_plan_entry_t **);
type_bridge_status_t type_bridge_migration_plan_approval_builder(const type_bridge_migration_plan_t *, type_bridge_migration_approval_builder_t **);
type_bridge_status_t type_bridge_migration_plan_authorize(const type_bridge_migration_plan_t *, const type_bridge_migration_approval_set_t *, type_bridge_migration_plan_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_plan_execute(const type_bridge_migration_plan_t *, const type_bridge_database_t *, type_bridge_byte_view_t, type_bridge_migration_execution_outcome_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_cancellation_new(type_bridge_migration_cancellation_t **);
type_bridge_status_t type_bridge_migration_cancellation_cancel(const type_bridge_migration_cancellation_t *);
type_bridge_status_t type_bridge_migration_cancellation_is_cancelled(const type_bridge_migration_cancellation_t *, uint8_t *);
type_bridge_status_t type_bridge_migration_cancellation_close(type_bridge_migration_cancellation_t **);
type_bridge_status_t type_bridge_migration_plan_execute_with_options(const type_bridge_migration_plan_t *, const type_bridge_database_t *, type_bridge_byte_view_t, const type_bridge_migration_execution_options_v1_t *, type_bridge_migration_execution_outcome_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_plan_close(type_bridge_migration_plan_t **);
type_bridge_status_t type_bridge_migration_plan_entry_identity(const type_bridge_migration_plan_entry_t *, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_plan_entry_safety(const type_bridge_migration_plan_entry_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_plan_entry_operation_count(const type_bridge_migration_plan_entry_t *, size_t *);
type_bridge_status_t type_bridge_migration_plan_entry_transaction_group_count(const type_bridge_migration_plan_entry_t *, size_t *);
type_bridge_status_t type_bridge_migration_plan_entry_backfill_count(const type_bridge_migration_plan_entry_t *, size_t *);
type_bridge_status_t type_bridge_migration_plan_entry_close(type_bridge_migration_plan_entry_t **);
type_bridge_status_t type_bridge_migration_approval_builder_approve(type_bridge_migration_approval_builder_t *, size_t, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_approval_builder_finish(type_bridge_migration_approval_builder_t *, type_bridge_migration_approval_set_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_approval_builder_close(type_bridge_migration_approval_builder_t **);
type_bridge_status_t type_bridge_migration_approval_set_count(const type_bridge_migration_approval_set_t *, size_t *);
type_bridge_status_t type_bridge_migration_approval_set_close(type_bridge_migration_approval_set_t **);
type_bridge_status_t type_bridge_migration_execution_outcome_direction(const type_bridge_migration_execution_outcome_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_execution_outcome_status(const type_bridge_migration_execution_outcome_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_execution_outcome_migration_identity(const type_bridge_migration_execution_outcome_t *, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_execution_outcome_position_kind(const type_bridge_migration_execution_outcome_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_execution_outcome_position_ordinal(const type_bridge_migration_execution_outcome_t *, size_t *, uint8_t *);
type_bridge_status_t type_bridge_migration_execution_outcome_diagnostics(const type_bridge_migration_execution_outcome_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_execution_outcome_backfill_count(const type_bridge_migration_execution_outcome_t *, size_t *);
type_bridge_status_t type_bridge_migration_execution_outcome_backfill_at(const type_bridge_migration_execution_outcome_t *, size_t, type_bridge_migration_backfill_observation_t **);
type_bridge_status_t type_bridge_migration_execution_outcome_close(type_bridge_migration_execution_outcome_t **);
type_bridge_status_t type_bridge_migration_backfill_observation_identity(const type_bridge_migration_backfill_observation_t *, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_backfill_observation_operation_ordinal(const type_bridge_migration_backfill_observation_t *, size_t *);
type_bridge_status_t type_bridge_migration_backfill_observation_manifest_step_index(const type_bridge_migration_backfill_observation_t *, size_t *);
type_bridge_status_t type_bridge_migration_backfill_observation_plan_digest(const type_bridge_migration_backfill_observation_t *, uint8_t *, size_t);
type_bridge_status_t type_bridge_migration_backfill_observation_direction(const type_bridge_migration_backfill_observation_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_backfill_observation_counts(const type_bridge_migration_backfill_observation_t *, uint64_t *, uint64_t *, uint64_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_backfill_observation_close(type_bridge_migration_backfill_observation_t **);
type_bridge_status_t type_bridge_migration_catalog_verify(const type_bridge_migration_catalog_t *, const type_bridge_database_t *, type_bridge_migration_verification_report_t **, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_verification_report_is_clean(const type_bridge_migration_verification_report_t *, uint8_t *);
type_bridge_status_t type_bridge_migration_verification_report_finding_count(const type_bridge_migration_verification_report_t *, size_t *);
type_bridge_status_t type_bridge_migration_verification_report_finding_at(const type_bridge_migration_verification_report_t *, size_t, type_bridge_migration_verification_finding_t **);
type_bridge_status_t type_bridge_migration_verification_report_frontier_count(const type_bridge_migration_verification_report_t *, size_t *);
type_bridge_status_t type_bridge_migration_verification_report_frontier_at(const type_bridge_migration_verification_report_t *, size_t, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_verification_report_close(type_bridge_migration_verification_report_t **);
type_bridge_status_t type_bridge_migration_verification_finding_kind(const type_bridge_migration_verification_finding_t *, uint32_t *);
type_bridge_status_t type_bridge_migration_verification_finding_pending_count(const type_bridge_migration_verification_finding_t *, size_t *);
type_bridge_status_t type_bridge_migration_verification_finding_pending_at(const type_bridge_migration_verification_finding_t *, size_t, type_bridge_migration_identity_t **);
type_bridge_status_t type_bridge_migration_verification_finding_diagnostics(const type_bridge_migration_verification_finding_t *, type_bridge_diagnostics_t **);
type_bridge_status_t type_bridge_migration_verification_finding_close(type_bridge_migration_verification_finding_t **);

#ifdef __cplusplus
}
#endif
