"""Type stubs for the ``type_bridge_core`` Rust extension.

Hand-maintained to mirror the PyO3 bindings in
``type-bridge-core/crates/python/src/lib.rs`` (and ``transpiler.rs``). Only the
symbols imported directly by the Python source carry precise signatures. The
remaining extension classes and functions are reached dynamically through the
``Any``-typed runtime loader (``type_bridge._rust_runtime.rust_core``) and are
exposed by the module-level ``__getattr__`` fallback rather than enumerated
here.
"""

from typing import Any

class ValueCoercer:
    def __init__(self) -> None: ...
    def coerce(self, value: Any, target_type: str) -> Any: ...
    def coerce_batch(self, pairs: list[tuple[Any, str]]) -> Any: ...
    def format_typeql(self, value: Any, value_type: str) -> str: ...

class QueryCompiler:
    def __init__(self) -> None: ...
    def compile(self, clauses: list[Any]) -> str: ...
    def compile_dicts(self, clauses: list[Any]) -> str: ...
    def parse(self, input: str) -> Any: ...

class TypeSchema:
    @staticmethod
    def from_typeql(input: str) -> TypeSchema: ...
    @staticmethod
    def from_json(json: str) -> TypeSchema: ...
    def to_json(self) -> str: ...
    def is_abstract(self, type_name: str) -> bool: ...
    def get_all_owned_attributes(self, name: str) -> Any: ...
    def get_all_plays_roles(self, name: str) -> Any: ...
    def get_all_relates(self, name: str) -> Any: ...
    def entities(self) -> Any: ...
    def relations(self) -> Any: ...
    def attributes(self) -> Any: ...
    def functions(self) -> Any: ...
    def structs(self) -> Any: ...
    def validate_query(self, clauses: list[Any]) -> Any: ...

class ValidationEngine:
    def __init__(self) -> None: ...
    def validate_type_name(self, name: str, context: str) -> bool: ...
    def validate_variable_name(self, name: str, context: str) -> bool: ...
    def validate_pattern(self, pattern: Any) -> bool: ...
    def validate_statement(self, statement: Any) -> bool: ...
    def validate_query(self, clauses: list[Any], schema: TypeSchema) -> Any: ...
    def add_rule(self, rule_dict: Any) -> None: ...
    def load_rules(self, json_str: str) -> list[str]: ...
    def export_rules(self) -> str: ...
    def clear_rules(self) -> None: ...
    def rule_count(self) -> int: ...
    def validate_entity(self, entity_data: Any, schema: TypeSchema | None = ...) -> Any: ...

def coerce_value(value: Any, target_type: str) -> Any: ...
def format_value(value: Any) -> str: ...
def parse_typeql_query(input: str) -> Any: ...
def toml_to_typeql(toml_text: str) -> str: ...
def __getattr__(name: str) -> Any: ...
